host: 0.0.0.0
port: 4000

name: ""
description: ""

# url: "https://findcongwang.github.io"
url: "http://localhost:4000"

paginate: 4
paginate_path: "page:num"

markdown: kramdown
permalink: pretty
highligher: null

future: true
gems: [jekyll-paginate]

# Disqus
disqus_short_name: findcongwang
disqus_show_comment_count: true

# Youtube
youtube_channel: CongWang-findcongwang
youtube_count_endpoint:

# LinkedIn
linkedin_page: findcongwang
linkedin_apikey: 78oj9n4xzq8b1o
linkedin_count_endpoint:

# Facebook
facebook_page: findcongwang
facebook_count_endpoint:

# Twitter
twitter_user: findcongwang
twitter_tweet_button: true
twitter_count_endpoint:

# Google Analytics
google_analytics_tracking_id: UA-99867423-1
